### ISSUE TITLE
ThermalExpansion recipes don't display properly in NEI

### ISSUE THREAD

**Issue by Lokilotus** [MachineMuse/MachineMusePowersuits#634]
NEI is displaying certian recipes incorrectly. For instance, the Control Circuit in NEI is missing the central item, which I've now found out to be a basic machine frame from TE. The parts can still be crafted using the proper recipe, once the blank spaces have been discovered and filled in with the proper TE parts.

Relavent Mod Versions:

MMMPS version 0.11.0.281
Numina version 0.4.0.119
ThermalExpansion version 4.0.3B1
NEI version 1.0.5.118

I can provide a full modlist on request.

It seems to be any recipe that uses the "registryName" tag in the recipes document that has this problem.

**Comment by Xen1290** [comment]
Mh, I've checked every recipe when I've rewritten the recipes, and registryName is used almost in every recipe. Can you provide a screen and also the modlist? also, your mod are Outdated (MPS/NEI). And, you can set in the config file to reset the recipes, maybe you have old recipe files.

**Comment by Lokilotus** [comment]
As an example, here's the recipe in the file for the servo:

"		"ingredients" : [
			[  null, { "oredictName" : "componentSolenoid" }, null ],
			[  { "oredictName" : "componentWiring" }, { "registryName" : "ThermalExpansion:material" }, { "oredictName" : "componentWiring" } ],
			[  null, { "oredictName" : "componentSolenoid" }, null ]
		],
		"result" : {
			"oredictName" : "componentServo"
		}
"

As you can see, it requires ThermalExpansion:material:0 (A TE pneumatic servo) in the centre of it to work.

Here are 3 screenshots:
1. NEI's version of the recipe in NEI ![mmmps1](https://cloud.githubusercontent.com/assets/2342253/10830631/789982b0-7e78-11e5-9de2-2d60fbe8235c.png)
2. Screenshot showing it does not work ![mmmps2](https://cloud.githubusercontent.com/assets/2342253/10830664/ca72e658-7e78-11e5-905a-92cb65907f82.png)
3. Screenshot showing that adding a TE servo (the central item as above) still works. ![mmmps3](https://cloud.githubusercontent.com/assets/2342253/10830671/d50a18b6-7e78-11e5-8519-864581737be2.png)

Modlist (copied from a recent forge crashlog, apologies for the formatting): http://pastebin.com/dxegpmKn

I'll try the config reset next time the server goes down, this weekend most likely. However, as we're playing with a custom modpack on a private server, it's kinda hard to update the mods as we've got quite a few people who don't know how to do so (I'm the server admin for MineSoc, the University of Sheffield MineCraft Society. This problem was highlighted to me by one of our members).

Anything else that you need, let me know.

**Comment by Xen1290** [comment]
Can you reproduce that thing in singleplayer? I tested with latest version of MPS/Numina/ThermalExpansion and I have no problem. I tested only in singleplayer because I haven't a server.

**Comment by Lokilotus** [comment]
In Singleplayer, the issue still seems to appear as above for me. I'm waiting on one of our members to test it but I suspect it will be the same result.

**Comment by aionys** [comment]
Regarding updating modpack for people who don't know how to:

1) Put your modpack as a private pack either on Feed The Beast or Technic
launcher- or both.
2) Make everyone switch to using that launcher instead, and give them the
link to the modpack so they can find it.
3) Release modpack updates whenever you like- next time a client tries to
launch, they will be informed that an update happened and ask if they'd
like to install it. The launcher will take of the update for them.

On Thu, Oct 29, 2015 at 2:53 PM, Lokilotus <notifications@github.com> wrote:

> In Singleplayer, the issue still seems to appear as above for me. I'm
> waiting on one of our members to test it but I suspect it will be the same
> result.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MachineMuse/MachineMusePowersuits/issues/634#issuecomment-152319628>
> .
>



-- 
mu'o mi'e .aionys.

.i.e'ucai ko cmima lo pilno be denpa bu .i doi.luk. mi patfu do zo'o
(Come to the Dot Side! Luke, I am your father. :D )

**Comment by lehjr** [comment]
Is the recipe actually valid and just not showing or is the recipe invalid and showing up that way? For me, none of the registry items are showing, just the oredict items. I suspect the issue is in Numina somewhere. In the past, I've used Minetweaker for MPS and MPSA recipes  as a workaround, but it really should be fixed the right way.

**Comment by Xen1290** [comment]
I can't reproduce that thing, in my instance (single player 200+ mods ) everything works. @MachineMuse

**Comment by lehjr** [comment]
@Xen1290 OK, but there are those people that can. Rather than bragging about how many mods you have installed, you could list the versions of them.

**Comment by Xen1290** [comment]
I'm from mobile, and for nei version sorry, my fault. All mods that I use are the latest version, at the moment, I can't Give you the list, but maybe this error is something with numina, like similar to this issue: https://github.com/MachineMuse/MachineMusePowersuits/issues/598

**Comment by lehjr** [comment]
Could very well be. There have been recipe issues for a long time.

**Comment by Lokilotus** [comment]
Possibly disproves the idea, although not totally I think: It still occurs with something without metadata, as far as I remember, so long as it's one of the things using registryName. So it's not the issue quoted above, but it may be related.

**Comment by lehjr** [comment]
No, but it could be Numina's parser in general.

**Comment by lehjr** [comment]
OK, so turns out I was running originally running with Numina version 0.4.0.119 as well (-_-). Don't know how I had a version that old unless I grabbed it from Curse instead of CurseForge. http://minecraft.curseforge.com/projects/numina/files
At least my MPS version is new. http://minecraft.curseforge.com/projects/numina/files

**Comment by flowtender** [comment]
So is this resolved in newer versions of Numina? I vaguely remember debugging this issue myself lol

**Comment by binnesman** [comment]
I was also having issues with recipes showing properly for all mods, TE, IC2, EnderIO, and vanilla. After updating to the beta version of Numina 0.4.0.131. I would recommend pushing this to an official release or something as unless people go to the files section of curseforge they will probably download build 0.4.0.119 and have recipe issues.

**Comment by Icepick869** [comment]
I was having this issue in single player and server using Numina 0.4.0.119. Updating to 0.4.0.131 resolved the singleplayer. I'm waiting on FTB to update our pack to find out if it fixes the server too. I'm going to assume it will.

**Comment by Mohl97** [comment]
It appears that this is a simple messup because of how curseforge works.

The most recent download is a beta one, which means that when you hit that big red button saying download, that downloads one a LOT of versions behind, where the problem isn't fixed.

I just fixed this by updating numina with the real latest version.

**Comment by lehjr** [comment]
Well, the curseforge link for Numina and MPS are both on the first post of the forums and on the readme here. AFAIK, the updates were originally marked as beta because they were under constant change. Things have slowed a bit as more things are fixed and working, but there are still fixes in the works, like the fix for compatibility with the Treecapitator mod, where the fix brings the minutes to cut down a spruce back down to seconds.

**Comment by flowtender** [comment]
ok, going to close this since it sounds like it was resolved, barring the issue with versioning on curseforge
